import time

print('kek cheburek!')
time.sleep(1)
print('kek cheburek!')
time.sleep(1)
print('kek cheburek!')
time.sleep(1)
print('kek cheburek!')
time.sleep(1)
print('kek cheburek!')
time.sleep(1)
print('kek cheburek!')
time.sleep(1)
print('kek cheburek!')
time.sleep(1)
print('kek cheburek!')
time.sleep(1)
print('kek cheburek!')
time.sleep(1)